networks:
  app-network:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: corn-bi-mysql
    restart: unless-stopped
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 30s
  backend:
    build:
      context: ./backend
    container_name: corn-bi-backend
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
    container_name: corn-bi-frontend
    restart: unless-stopped
    networks:
      - app-network
  nginx:
    image: nginx:1.27-alpine
    container_name: corn-bi-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
      