services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  backend:
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: -Xmx512m -Xms256m
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MYSQL_DATASOURCE_URL: ${MYSQL_DATASOURCE_URL}
      MYSQL_DATASOURCE_USERNAME: ${MYSQL_DATASOURCE_USERNAME}
      MYSQL_DATASOURCE_PASSWORD: ${MYSQL_DATASOURCE_PASSWORD}
      AUTH_TOKEN_SECRET: ${AUTH_TOKEN_SECRET}
      APP_CORS_ALLOWED_ORIGINS: ${APP_CORS_ALLOWED_ORIGINS}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
  frontend:
    build:
      args:
        APP_API_BASE_URL: ${APP_API_BASE_URL}
