# 定义后端服务池，命名为backend_api
# 池中有一个节点（backend是容器名，Docker内置DNS将backend解析成容器的IP）
# 与后端服务器最多32个空闲长连接，复用TCP，减少握手开销
upstream backend_api{
    server backend:8080;
    keepalive 32;
}

upstream frontend_static{
    server frontend:80;
    keepalive 16;
}

# 定义一个虚拟主机
server{
    # 监听本Nginx容器内的80端口
    listen 80;
    server_name _;

    # 请求体大小的最大值
    client_max_body_size 20m;

    # 匹配所有以/api/开头的请求
    location /api/ {
        # 路径原样转发
        # 这里不能写成http://backend_api/，Nginx会切割/api/部分；
        # 最终错误转发成http://backend:8080/user/login
        proxy_pass http://backend_api;
        # HTTP/1.0默认每次请求后都直接断开，因此升级到1.1并将Connection头置空
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        # 把用户请求的原始Host传递给后端服务器
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        # 追加客户端真实IP，服务器可以用此记录访问者IP
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # 将原始协议传递给后端服务器
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 30s;
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
    }

    location / {
        proxy_pass http://frontend_static;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Nginx的location匹配规则，默认前缀越长越优先
}