# Web?????
server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api # ?????http://localhost:8080/api/xxx
springdoc:
  api-docs:
    path: /v3/api-docs # OpenAPI??JSON?????
  swagger-ui:
    path: /swagger-ui/index.html # # SwaggerUI???????
    tags-sorter: alpha # API????????????????
    operations-sorter: method # API????????HTTP????